{
	"name": "root",
	"classes": [
		{
			"name": "TestCase",
			"pos": {
				"line": 10,
				"file": "src/test/TestMain.hx"
			},
			"id": "TestCase",
			"methods": [
				{
					"name": "testError",
					"line": 20,
					"executionTime": 0,
					"errorLine": null,
					"state": "error",
					"message": "failure\nCalled from local function #4 (src/test/TestMain.hx line 21 column 2)\nCalled from TestCase.testError (src/test/TestMain.hx line 22 column 3)",
					"timestamp": 1621614276.9624224
				},
				{
					"name": "testFailure",
					"line": 15,
					"executionTime": 0,
					"errorLine": 16,
					"state": "failure",
					"message": "expected \"A\" but it is \"B\"",
					"timestamp": 1621614276.9624224
				},
				{
					"name": "testEmpty",
					"line": 24,
					"executionTime": 0,
					"errorLine": null,
					"state": "failure",
					"message": "no assertions",
					"timestamp": 1621614276.9624224
				},
				{
					"name": "testIgnore",
					"line": 27,
					"executionTime": 0,
					"errorLine": null,
					"state": "ignore",
					"message": "Description",
					"timestamp": 1621614276.9624224
				},
				{
					"name": "testSuccess",
					"line": 11,
					"executionTime": 0,
					"errorLine": null,
					"state": "success",
					"message": null,
					"timestamp": 1621614276.9624224
				}
			]
		},
		{
			"name": "TestCase2",
			"pos": {
				"line": 30,
				"file": "src/test/TestMain.hx"
			},
			"id": "TestCase2",
			"methods": [
				{
					"name": "testSuccess",
					"line": 31,
					"executionTime": 0,
					"errorLine": null,
					"state": "success",
					"message": null,
					"timestamp": 1621614276.9624224
				}
			]
		}
	]
}